language: cpp
compiler:
  - gcc
  - clang
before_install: 
  - git submodule update --init --recursive
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
script:
  - (mkdir -p build/06 && cd build/06 && qmake ../../Assignment06Filtering && make)
